interface/urls.py
from django.urls import path

from . import views

app_name = 'interface'

urlpatterns = [
    path('', views.survivors, name='survivors'),
    path('<int:pk>/', views.survivor_detail, name='survivor_detail'),
    path(
        '<int:pk>/report-infected/',
        views.report_infected,
        name='report_infected',
    ),
    path(
        '<int:pk>/update-location/',
        views.update_location,
        name='update_location',
    ),
    path('<int:pk>/make-trade/', views.make_trade, name='make_trade'),
    path('add-survivor/', views.add_survivor, name='add_survivor'),
    path(
        '<int:pk>/update-location/',
        views.update_location,
        name='update_location',
    ),
    path('resources-report/', views.resources_report, name='resources_report'),
]

zssn/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers

from api.views import SurvivorViewSet

router = routers.DefaultRouter()
router.register(r'survivors', SurvivorViewSet, basename='survivors')

urlpatterns = [
    path('', include('interface.urls')),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
]

interface/views.py
import requests
from django.shortcuts import redirect, render
from django.urls import reverse



def survivors(request):
    response = requests.get('https://zssn.onrender.com/api/survivors/')
    survivors = response.json()
    context = {'survivors': survivors}
    return render(request, 'interface/survivors.html', context)


def survivor_detail(request, pk):
    response = requests.get(f'https://zssn.onrender.com/api/survivors/{pk}/')
    survivor = response.json()

    response = requests.get(f'https://zssn.onrender.com/api/survivors/')
    survivors = response.json()


    context = {'survivor': survivor, 'survivors': survivors}
    return render(request, 'interface/survivor_detail.html', context)


def resources_report(request):
    response = requests.get(
        'https://zssn.onrender.com/api/survivors/get_resources_report/'
    )
    context = {'report': response.json()}
    return render(request, 'interface/resources_report.html', context)


def report_infected(request, pk):
    data = {
        'survivor_reported': request.POST.get('survivor_reported'),
    }
    response = requests.put(
        f'https://zssn.onrender.com/api/survivors/{pk}/report_infected/', json=data
    )
    return redirect(reverse('interface:survivor_detail', kwargs={'pk': pk}))


def update_location(request, pk):
    if request.method == 'POST':
        latitude = request.POST.get('latitude')
        longitude = request.POST.get('longitude')
        data = {'latitude': latitude, 'longitude': longitude}
        requests.patch(f'https://zssn.onrender.com/api/survivors/{pk}/', data=data)
        return redirect(
            reverse('interface:survivor_detail', kwargs={'pk': pk})
        )
    response = requests.get(f'https://zssn.onrender.com/api/survivors/{pk}/')
    survivor = response.json()
    return render(
        request, 'interface/update_location.html', {'survivor': survivor}
    )


def add_survivor(request):
    if request.method == 'POST':
        data = {
            'name': request.POST.get('name'),
            'age': request.POST.get('age'),
            'gender': request.POST.get('gender'),
            'latitude': request.POST.get('latitude'),
            'longitude': request.POST.get('longitude'),
            'water': request.POST.get('water'),
            'food': request.POST.get('food'),
            'medication': request.POST.get('medication'),
            'ammunition': request.POST.get('ammunition'),
            'is_infected': request.POST.get('is_infected', False),
            'total_points': 0,
            'received_reports': 0,
        }
        requests.post('https://zssn.onrender.com/api/survivors/', data=data)
        return redirect(reverse('interface:survivors'))
    return render(request, 'interface/add_survivor.html')


def make_trade(request, pk):
    if request.method == 'POST':
        data = {
            'survivor1': pk,
            'survivor2': request.POST['survivor2'],
            'survivor1_items': request.POST.getlist('survivor1_items'),
            'survivor2_items': request.POST.getlist('survivor2_items'),
        }

        requests.post(
            f'https://zssn.onrender.com/api/survivors/make_trade/', data=data
        )
        return redirect(
            reverse('interface:survivor_detail', kwargs={'pk': pk})
        )

    response = requests.get(f'https://zssn.onrender.com/api/survivors/{pk}/')
    survivor1 = response.json()

    response = requests.get(
        f'https://zssn.onrender.com/api/survivors/{request.GET["survivor2"]}/'
    )
    survivor2 = response.json()

    context = {'survivor1': survivor1, 'survivor2': survivor2}
    return render(request, 'interface/make_trade.html', context)

interface/templates/interface/add_survivor.html
{% extends 'interface/base.html' %}
{% block content %}
<div tabindex="0" class="content" onfocus="closeSidebar()" id="content">
    <div class="title-container">
        <h1>Add a Survivor</h1>
    </div>
    <div class="add-survivor-container">
        <div class="add-form-container">
            <form action="{% url 'interface:add_survivor' %}" method="POST">
                {% csrf_token %}
                <label for="name">Name:</label>
                <input type="text" id="name" name="name">
                <br>
                <label for="age">Age:</label>
                <input type="number" id="age" name="age">
                <br>
                <label for="gender">Gender:</label>
                <select name="gender" id="gender">
                    <option value="F">Male</option>
                    <option value="M">Female</option>
                </select>
                <br><br>
                <label>Location: </label><br>
                latitude: <input type="text" id="latitude" name="latitude"><br>
                longitude: <input type="text" id="longitude" name="longitude"><br>
                <br><br>
                infected: <input type="checkbox" name="infected" id="infected" value="True" default="False">
                <br><br>
                <label>Inventory:</label><br>
                water: <input type="text" id="water" name="water"><br>
                food: <input type="text" id="food" name="food"><br>
                medication: <input type="text" id="medication" name="medication"><br>
                ammunition: <input type="text" id="ammunition" name="ammunition"><br>
                <br>
                <input type="submit" value="Add">
            </form>
        </div>
        <br>
        <a href="{% url 'interface:survivors' %}">Back</a>
    </div>
</div>

{% endblock %}

interface/templates/interface/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Zombie Survival Social Network</title>
    <link rel="icon" href="{% static 'assets/umbrella-favico.ico' %}">
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
</head>
<body>
    <main>
        {% include 'interface/partials/_header.html' %}
        {% block content %}{% endblock %}
    </main>
</body>
<script src="{% static 'js/sidebar.js' %}"></script>
</html>

interface/templates/interface/make_trade.html
{% extends 'interface/base.html' %}
{% block content %}
<div tabindex="0" class="content" onfocus="closeSidebar()" id="content">
  <div class="trade">
    <div class="survivor-trade-container">
      <h2>{{ survivor1.name }}</h2>
      <p>Points: {{ survivor1.total_points }}</p>
      <p>Water: {{ survivor1.water }}</p>
      <p>Food: {{ survivor1.food }}</p>
      <p>Medication: {{ survivor1.medication }}</p>
      <p>Ammunition: {{ survivor1.ammunition }}</p>
      <h2>{{ survivor2.name }}</h2>
      <p>Points: {{ survivor2.total_points }}</p>
      <p>Water: {{ survivor2.water }}</p>
      <p>Food: {{ survivor2.food }}</p>
      <p>Medication: {{ survivor2.medication }}</p>
      <p>Ammunition: {{ survivor2.ammunition }}</p>
    </div>
    <div class="trade-container">
      {% csrf_token %}
      <div class="trade-items">
        <h2>Items to trade</h2>
        <form method="post" action="{% url 'interface:make_trade' survivor1.id %}">
          <div class="resources">
            <label>Water: <input type="number" name="survivor1_items" value="0"></label>
            <label>Food: <input type="number" name="survivor1_items" value="0"></label>
            <label>Medication: <input type="number" name="survivor1_items" value="0"></label>
            <label>Ammunition: <input type="number" name="survivor1_items" value="0"></label>
          </div>
          <h2>Items to receive</h2>
          <div class="resources">
            <label>Water: <input type="number" name="survivor2_items" value="0"></label>
            <label>Food: <input type="number" name="survivor2_items" value="0"></label>
            <label>Medication: <input type="number" name="survivor2_items" value="0"></label>
            <label>Ammunition: <input type="number" name="survivor2_items" value="0"></label>
          </div>
        <input type="hidden" name="survivor2" value="{{ survivor2.id }}">
        <input type="submit" value="Make trade">
      </form>
    </div>
  </div>
</div>
{% endblock %}

interface/templates/interface/resources_report.html
{% extends 'interface/base.html' %}
{% block content %}
<div tabindex="0" class="content" onfocus="closeSidebar()" id="content">
  <div class="title-container">
    <h1>Survivors Resources Report</h1>
  </div>
  <div class="resources-reports-table-container">
    <table>
      <thead>
        <tr>
          <th>Resource</th>
          <th>Total</th>
          <th>Average</th>
        </tr>
      </thead>
      <tbody>
        {% for resource, data in report.resources.items %}
        <tr>
          <td>{{ resource }}</td>
          <td>{{ data.total }}</td>
          <td>{{ data.average }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="resources-reports-container">
      <p>Total Population: <u>{{ report.population.total }}</u></p>
      <p>Infected: <u>{{ report.population.infected }}</u></p>
      <p>Non-Infected: <u>{{ report.population.non_infected }}</u></p>
      <p>Percent infected: <u>{{ report.population.percent_infected }}%</u></p>
      <p>Percent non-infected: <u>{{ report.population.percent_non_infected }}%</u></p>
      <p>Total points lost: <u>{{ report.total_points_lost }}</u></p>
    </div>
  </div>
</div>
{% endblock %}

interface/templates/interface/survivor_detail.html
{% extends 'interface/base.html' %}
{% block content %}
<div tabindex="0" class="content" onfocus="closeSidebar()" id="content">
  <div class="title-container">
    <h1>Survivor Detail</h1>
  </div>
  <div class="detailed-table-container">
    <table>
      <thead>
          <tr>
              <th>Name</th>
              <th>Age</th>
              <th>Gender</th>
              <th>Latitude</th>
              <th>Longitude</th>
              <th>Infected</th>
              <th>Total Points</th>
              <th>Received Reports</th>
          </tr>
      </thead>
      <tbody>
          <tr>
              <td>{{ survivor.name }}</td>
              <td>{{ survivor.age }}</td>
              <td>{{ survivor.gender }}</td>
              <td>{{ survivor.latitude }}</td>
              <td>{{ survivor.longitude }}</td>
              <td>{{ survivor.is_infected }}</td>
              <td>{{ survivor.total_points }}</td>
              <td>{{ survivor.received_reports }}</td>
          </tr>
      </tbody>
  </table>
  <table>
    <thead>
        <tr>
            <th>Water</th>
            <th>Food</th>
            <th>Medication</th>
            <th>Ammunition</th>
        </tr>
    </thead>
    <tbody>
      <tr>
          <td>{{ survivor.water }}</td>
          <td>{{ survivor.food }}</td>
          <td>{{ survivor.medication }}</td>
          <td>{{ survivor.ammunition }}</td>
      </tr>
  </tbody>
  </table>
  <div class="actions-container">
    <h2>Actions</h2>
    <a href="{% url 'interface:update_location' survivor.id %}">Update Location</a>
    <form action="{% url 'interface:make_trade' survivor.id %}" method="get">
      {% csrf_token %}
      Select a survivor: <select name="survivor2" id="survivor2">
      {% for survivor in survivors %}
        <option value="{{ survivor.id }}">{{ survivor.name }} | Reports: {{ survivor.received_reports }}</option>
      {% endfor %}
      </select>
      <input type="submit" value="Make a Trade">
    </form>
    <form action="{% url 'interface:report_infected' survivor.id %}" method="post">
      {% csrf_token %}
      Select a survivor: <select name="survivor_reported" id="survivor_reported">
      {% for survivor in survivors %}
        <option value="{{ survivor.id }}">{{ survivor.name }} | Reports: {{ survivor.received_reports }}</option>
      {% endfor %}
      </select>
      <input type="submit" value="Report Infected">
    </form>
    </div>
  </div>
  </div>
{% endblock %}

interface/templates/interface/survivors.html
{% extends 'interface/base.html' %}
{% block content %}
<div tabindex="0" class="content" onfocus="closeSidebar()" id="content">
    <div class="title-container">
        <h1>Survivors</h1>
    </div>
    <div class="table-container">
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Age</th>
                    <th>Gender</th>
                    <th>Latitude</th>
                    <th>Longitude</th>
                    <th>Infected</th>
                    <th>Total Points</th>
                    <th>Received Reports</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for survivor in survivors %}
                <tr>
                    <td>{{ survivor.name }}</td>
                    <td>{{ survivor.age }}</td>
                    <td>{{ survivor.gender }}</td>
                    <td>{{ survivor.latitude }}</td>
                    <td>{{ survivor.longitude }}</td>
                    <td>{{ survivor.is_infected }}</td>
                    <td>{{ survivor.total_points }}</td>
                    <td>{{ survivor.received_reports }}</td>
                    <td>
                        <a href="{% url 'interface:survivor_detail' survivor.id %}">Detail</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="add-survivor-container">
        <a href="{% url 'interface:add_survivor' %}">Add New Survivors</a>
    </div>
</div>
{% endblock %}

interface/templates/interface/update_location.html
{% extends 'interface/base.html' %}
{% block content %}
<div tabindex="0" class="content" onfocus="closeSidebar()" id="content">
    <div class="title-container">
        <h1>Update Location</h1>
    </div>
    <div class="form-container">
        <form action="{% url 'interface:update_location' survivor.id %}" method="POST">
            {% csrf_token %}
            <label for="latitude">Latitude:</label>
            <input type="text" id="latitude" name="latitude" value="{{ survivor.latitude }}">
            <label for="longitude">Longitude:</label>
            <input type="text" id="longitude" name="longitude" value="{{ survivor.longitude }}">
            <input type="submit" value="Update">
        </form>
    </div>
</div>
{% endblock %}