interface/urls.py
from django.urls import path

from . import views

app_name = 'interface'

urlpatterns = [
    path('', views.survivors, name='survivors'),
    path('<int:pk>/', views.survivor_detail, name='survivor_detail'),
    path(
        '<int:pk>/report-infected/',
        views.report_infected,
        name='report_infected',
    ),
    path(
        '<int:pk>/update-location/',
        views.update_location,
        name='update_location',
    ),
    path('<int:pk>/make-trade/', views.make_trade, name='make_trade'),
    path('add-survivor/', views.add_survivor, name='add_survivor'),
    path(
        '<int:pk>/update-location/',
        views.update_location,
        name='update_location',
    ),
    path('resources-report/', views.resources_report, name='resources_report'),
]

zssn/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers

from api.views import SurvivorViewSet

router = routers.DefaultRouter()
router.register(r'survivors', SurvivorViewSet, basename='survivors')

urlpatterns = [
    path('', include('interface.urls')),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
]

interface/views.py
import requests
from django.shortcuts import redirect, render
from django.urls import reverse



def survivors(request):
    response = requests.get('https://zssn.onrender.com/api/survivors/')
    survivors = response.json()
    context = {'survivors': survivors}
    return render(request, 'interface/survivors.html', context)


def survivor_detail(request, pk):
    response = requests.get(f'https://zssn.onrender.com/api/survivors/{pk}/')
    survivor = response.json()

    response = requests.get(f'https://zssn.onrender.com/api/survivors/')
    survivors = response.json()


    context = {'survivor': survivor, 'survivors': survivors}
    return render(request, 'interface/survivor_detail.html', context)


def resources_report(request):
    response = requests.get(
        'https://zssn.onrender.com/api/survivors/get_resources_report/'
    )
    context = {'report': response.json()}
    return render(request, 'interface/resources_report.html', context)


def report_infected(request, pk):
    data = {
        'survivor_reported': request.POST.get('survivor_reported'),
    }
    response = requests.put(
        f'https://zssn.onrender.com/api/survivors/{pk}/report_infected/', json=data
    )
    return redirect(reverse('interface:survivor_detail', kwargs={'pk': pk}))


def update_location(request, pk):
    if request.method == 'POST':
        latitude = request.POST.get('latitude')
        longitude = request.POST.get('longitude')
        data = {'latitude': latitude, 'longitude': longitude}
        requests.patch(f'https://zssn.onrender.com/api/survivors/{pk}/', data=data)
        return redirect(
            reverse('interface:survivor_detail', kwargs={'pk': pk})
        )
    response = requests.get(f'https://zssn.onrender.com/api/survivors/{pk}/')
    survivor = response.json()
    return render(
        request, 'interface/update_location.html', {'survivor': survivor}
    )


def add_survivor(request):
    if request.method == 'POST':
        data = {
            'name': request.POST.get('name'),
            'age': request.POST.get('age'),
            'gender': request.POST.get('gender'),
            'latitude': request.POST.get('latitude'),
            'longitude': request.POST.get('longitude'),
            'water': request.POST.get('water'),
            'food': request.POST.get('food'),
            'medication': request.POST.get('medication'),
            'ammunition': request.POST.get('ammunition'),
            'is_infected': request.POST.get('is_infected', False),
            'total_points': 0,
            'received_reports': 0,
        }
        requests.post('https://zssn.onrender.com/api/survivors/', data=data)
        return redirect(reverse('interface:survivors'))
    return render(request, 'interface/add_survivor.html')


def make_trade(request, pk):
    if request.method == 'POST':
        data = {
            'survivor1': pk,
            'survivor2': request.POST['survivor2'],
            'survivor1_items': request.POST.getlist('survivor1_items'),
            'survivor2_items': request.POST.getlist('survivor2_items'),
        }

        requests.post(
            f'https://zssn.onrender.com/api/survivors/make_trade/', data=data
        )
        return redirect(
            reverse('interface:survivor_detail', kwargs={'pk': pk})
        )

    response = requests.get(f'https://zssn.onrender.com/api/survivors/{pk}/')
    survivor1 = response.json()

    response = requests.get(
        f'https://zssn.onrender.com/api/survivors/{request.GET["survivor2"]}/'
    )
    survivor2 = response.json()

    context = {'survivor1': survivor1, 'survivor2': survivor2}
    return render(request, 'interface/make_trade.html', context)

interface/templates/interface/partials/_header.html
{% load static %}
<header>
    <div class="header" id="header">
        <button onclick="toggleSidebar()" class="btn-icon-header" aria-label="Open Sidebar">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
            </svg>
        </button>
        <div class="logo-header">
            <a href="{% url 'interface:survivors' %}">
                <img class= img-logo-header src="{% static 'assets/umbrella-logo.png' %}" alt="Umbrella Corporation Logo">
            </a>
        </div>
        <div class="navigation-header" id="navigation-header">
            <button onclick="toggleSidebar()" class="btn-icon-header" aria-label="Close Sidebar">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-x" viewBox="0 0 16 16">
                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                </svg>
            </button>
            <a href="{% url 'interface:survivors' %}">Survivors</a>
            <a href="{% url 'interface:resources_report' %}">Resources Report</a>
        </div>
    </div>
</header>